#
# Makefile for Yamada Custom Android Drivers
#

obj-$(CONFIG_OCHINAI_INAHO_AUDIO) += ochinai_inaho_audio.o
obj-$(CONFIG_SPARXIE_SWAP_TUNER) += sparxie_swapiness_tuner.o
obj-$(CONFIG_RACO_RC_OVERRIDE) += raco_rc_override.o
obj-$(CONFIG_PAVOLIA_REINE_RESETPROP) += pavolia_reine_resetprop.o
obj-$(CONFIG_SANDEVISTAN_BOOT) += sandevistan_boot.o
obj-$(CONFIG_YAMADA_GAMING_BOOST) += yamada_gaming_boost.o
obj-$(CONFIG_YAMADA_TENEBRION) += tenebrion.o
obj-$(CONFIG_SCHEDUTIL_ENFORCER) += schedutil_enforcer.o
obj-$(CONFIG_YAMADA_DEV_IDENTIFICATION) += yamada_dev_identification.o